# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 09:58
from __future__ import unicode_literals

from django.db import migrations

# TODO: do something to smartly capture everything 


def add_initial_channel_groupings(apps, schema_editor):
    user = apps.get_model("auth", "User")
    foreign_grouping = apps.get_model("all_models", "ModelWithForeignKeyToUser0")
    user = user.objects.create(
        username='username',
        email='hello@mail.com',
        first_name='a',
        last_name='b',
    )

    for n in range(100):
        foreign_grouping.objects.create(user=user, value=n)


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_channel_groupings)
    ]
