# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0002_auto_20161004_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelwithforeignkeytouser0',
            name='value',
        ),
    ]
